title: My Portolio
author: Ben Ricchio
email: bricchio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my site!  This is a place for you to browse the various 
  branded career websites I've built at Jobvite over the past 3 years.
  Click on any tile to see my work.  Enjoy!

# social links
linkedin_username: ben-ricchio
twitter_username: ben_ricchio # DO NOT include the @ character, or else the build will fail!
github_username:  bricchio # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
